version: '3.8'

services:
  mobile:
    build:
      context: ./mobile
    environment:
      CHOKIDAR_USEPOLLING: 1 
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      # - ./mobile/app:/app
      # - notused:/app/node_modules
      # - type: bind
      #   source: ./mobile/app/app.json
      #   target: /app/app.json
      - ./mobile/app/src:/app/src
    env_file:
      - .env/.mobile.env

  backend:
    build: ./backend
    env_file:
      - .env/.backend.env

# volumes:
#   notused: