version: '3.8'

services:
  db:
    image: postgres
    volumes: 
      - backend-data:/var/lib/postgresql/data/
    env_file:
      - .env/.db.env
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env/.backend.env
    depends_on:
      - db

volumes:
  backend-data: